# do this last.
PROGS = 0-ns-to-cycles.c
PROGS += 1-const-problems.c

# not really a puzzle, but an example of how to do.
PROGS += cycles-per-sec.c
PROGS := 2-weird-timing.c

# worth playing with different ones.
OPT_LEVEL = -Ofast
OPT_LEVEL = -O3
OPT_LEVEL = -O2


RUN = 1

include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3

