PROGS = 0-circular-example.c 1-circular-example32.c

# automatically run the code
RUN = 1

# if you need to override the install
BOOTLOADER = my-install

include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3
