# SUPPORT_OBJS := 
PROGS = runtime-inline.c

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install

COMMON_SRC = runtime-inline-asm.S
# START = ./getput-start.o

# uncomment if you want it to automatically run.
RUN=1


include $(CS240LX_2026_PATH)/libpi/mk/Makefile.robust-v3
